

import type { Metadata } from "next";
import "./globals.css";
import HeaderTemplate from "@/components/templates/HeaderTemplate"
import FooterTemplate from "@/components/templates/FooterTemplate"

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="scroll-smooth">
      <body className="bg-gradient-to-br from-blue-50 to-purple-50">
        <div>
          {/* Navbar */}
          <HeaderTemplate />

          {/* Main content */}
          <main>
            {children}
          </main>

          {/* Footer */}
          <FooterTemplate/>
        </div>
      </body>
    </html>
  );
}
